name: Deploy Infrastructure

on:
  push:
    branches: [ main ]
    paths:
      - 'cdk/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
          mask-aws-account-id: false

      # AWSアカウントIDを環境変数として設定
      - name: Set AWS Account ID
        run: |
          echo "AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)" >> $GITHUB_ENV

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install CDK dependencies
        run: |
          cd cdk
          rm -rf node_modules package-lock.json
          npm install

      - name: Bootstrap CDK
        env:
          CDK_DEFAULT_ACCOUNT: ${{ env.AWS_ACCOUNT_ID }}
          CDK_DEFAULT_REGION: ap-northeast-1
        run: |
          cd cdk
          npx cdk bootstrap aws://${{ env.AWS_ACCOUNT_ID }}/ap-northeast-1

      - name: Deploy with CDK
        env:
          CDK_DEBUG: true
          CDK_DEFAULT_ACCOUNT: ${{ env.AWS_ACCOUNT_ID }}
          CDK_DEFAULT_REGION: ap-northeast-1
        run: |
          cd cdk
          npm run build
          npx cdk deploy --require-approval never --verbose 