name: Deploy Infrastructure

on:
  push:
    branches: [ main ]
    paths:
      - 'cdk/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
          mask-aws-account-id: false

      # AWSアカウントIDを環境変数として設定
      - name: Set AWS Account ID
        run: |
          echo "AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)" >> $GITHUB_ENV

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install CDK dependencies
        run: |
          cd cdk
          rm -rf node_modules package-lock.json
          npm install

      - name: Bootstrap CDK
        env:
          CDK_DEFAULT_ACCOUNT: ${{ env.AWS_ACCOUNT_ID }}
          CDK_DEFAULT_REGION: ap-northeast-1
        run: |
          cd cdk
          npx cdk bootstrap aws://${{ env.AWS_ACCOUNT_ID }}/ap-northeast-1

      # IAM権限の確認
      - name: Check IAM permissions
        run: |
          aws iam get-user
          aws sts get-caller-identity

      - name: Check CDK Bootstrap
        run: |
          cd cdk
          # CDKブートストラップスタックの状態を確認
          aws cloudformation describe-stacks --stack-name CDKToolkit || true

      - name: Check Stack Status
        run: |
          cd cdk
          # アプリケーションスタックの状態を確認
          aws cloudformation describe-stacks --stack-name LambdaLaravelStack || true
          # スタックのイベントを確認
          aws cloudformation describe-stack-events --stack-name LambdaLaravelStack || true

      - name: Deploy with CDK
        env:
          CDK_DEBUG: true
          CDK_DEFAULT_ACCOUNT: ${{ env.AWS_ACCOUNT_ID }}
          CDK_DEFAULT_REGION: ap-northeast-1
          CDK_STACK_NAME: LambdaLaravelStack
          DEBUG: '*'
        run: |
          cd cdk
          npx cdk deploy LambdaLaravelStack \
            --require-approval never \
            --verbose \
            --trace \
            --debug

      - name: Build TypeScript
        run: |
          cd cdk
          npm run build -- --verbose 